<template>
    <div class="col-lg">
        <div class="alert alert-secondary br-0 infoComponent">
            <h4>Upload your dependency tree here</h4>
            <hr>
            <div class="m-0">
                <p class="m-0">Open up your preferred commandline tool, navigate to your project and type</p>
                <pre class="m-0 alert alert-light mt-2 mb-2 br-0">mvn dependency:tree -Doutput=/path/to/file.txt</pre>
                <p class="m-0">Example:</p>
                <pre
                    class="m-0 alert alert-light mt-2 mb-2 br-0">mvn dependency:tree -DoutputFile=temp/mvn_dependency_tree.txt</pre>
                <p>this will create a temp folder in your project directory with the file you need to upload
                    here.
                </p>
                <br></div>
            <span
                style="font-weight: bold;">The file to be uploaded is required to be the file generated by the previously mentioned command!</span>
            <br>
            <div class="input-group mb-3 mt-3">
                <div class="custom-file br-0">
                    <FileReader @load="file = $event"></FileReader>
                </div>
            </div>
            <button type="button" class="btn btn-secondary br-0" style="width: 100%" @click="sendData">Find
                conflicts
            </button>


            <div class="mt-4 br-0" style="overflow: auto" v-if="conflictCount > 0">
                <hr>
                <h4>
                    Found {{ conflictCount }} confliction set<span v-if="conflictCount > 1">s</span>
                    in your build.</h4>
                <small class="handPointer" @click="seeConflictsBtn">Click here to see your conflicts</small>
                <hr>
                <div v-if="seeConflicts === true">
                <div class="alert alert-light br-0 " v-for="(conflict, firstindex) in conflictObj" :key="firstindex" >
                    <div class="" style="color: black">
                        <div class="">
                            <h5>This maven dependency has {{ conflict.conflicts.length }} conflict<span
                                v-if="conflict.conflicts.length > 1">s</span></h5>
                            <hr>
                            <div>
                                <p><span class="bolder">Group ID:</span> {{ conflict.firstOccurance.GroupId }}</p>
                                <p><span class="bolder">Artifact ID:</span> {{ conflict.firstOccurance.ArtifactId }}</p>
                            </div>
                        </div>
                        <div class="row" v-for="(obj, secondindex) in conflict.conflicts" :key="secondindex"
                             style="margin: 0; overflow: auto">
                            <div class="alert alert-light br-0 col-sm "
                                 style="border: black solid 1px;color: black;">
                                <p class="bolder">Version: <br><span
                                    style="font-weight: normal">{{ conflict.firstOccurance.Version }}</span>
                                </p>

                                <button class="btn btn-outline-dark br-0"
                                        style="width: 100%; padding: 10px; margin: 0"
                                        @click="conflictTreeView(conflictObj[firstindex].firstOccuranceJsonMap)">
                                    See the project structure containing this dependency
                                </button>
                            </div>
                            <div class="alert alert-light br-0 col-sm ml-2"
                                 style="border: black solid 1px;color: black;">
                                <p class="bolder">Version: <br> <span
                                    style="font-weight: normal">{{ obj.Version }}</span></p>
                                <button class="btn btn-outline-dark br-0" style="width: 100%; padding: 10px; margin: 0"
                                        @click="conflictTreeView(conflict.jsonMap)">
                                    See the project structure containing this dependency
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script src="./Information.js"></script>

<style scoped>

</style>