<template>
  <div class="container-fluid mt-3 " id="app" style="padding-left: 5%; padding-right: 5%">
    <div class="jumbotron mt-0 mb-1 rrc" style="background-color: #F7F8F9">
      <div class="container-fluid p-5 pl-3">
        <h1 class="display-4">Maven Conflicts - Found the easy way</h1>
        <p class="lead">The simple way to get a good overview of your dependency tree and find version conflicts
          in your maven builds.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm col-md">
        <div class="alert alert-secondary mb-3 mt-0 rrc"
             style="text-align: center; background-color: #F7F8F9; padding-bottom: 18px">
          <h4>Upload your dependency tree here</h4>
          <hr>
          <div class="m-0">
            <p class="m-0">Open up your preferred commandline tool, navigate to your project and type</p>
            <pre class="m-0 alert alert-light mt-2 mb-2 rrc">mvn dependency:tree -Doutput=/path/to/file.txt</pre>
            <p class="m-0">Example:</p>
            <pre
                class="m-0 alert alert-light mt-2 mb-2 rrc">mvn dependency:tree -DoutputFile=temp/mvn_dependency_tree.txt</pre>
            <p>this will create a temp folder in your project directory with the file you need to upload
              here.
            </p>
            <br></div>
          <span
              style="font-weight: bold;">The file to be uploaded is required to be the file generated by the previously mentioned command!</span>
          <br>
          <div class="input-group mb-3 mt-3">
            <div class="custom-file rrc">
              <file-reader @load="file = $event"></file-reader>
            </div>
          </div>
          <button type="button" class="btn btn-secondary rrc" style="width: 100%" @click="sendData">Find
            conflicts
          </button>


          <div class="mt-4 rrc" style="overflow: auto" v-if="conflictCount > 0">
            <hr>
            <h4>Found {{ conflictCount }} confliction set<span v-if="conflictCount > 1">s</span> in your build.</h4>
            <hr>
            <div class="alert alert-light rrc " v-for="(conflict, firstindex) in conflictObj" :key="firstindex">
              <div class="" style="color: black">
                <div class="">
                  <h5>This maven dependency has {{ conflict.conflicts.length }} conflict<span
                      v-if="conflict.conflicts.length > 1">s</span></h5>
                  <hr>
                  <div>
                    <p><span class="bolder">Group ID:</span> {{ conflict.firstOccurance.GroupId }}</p>
                    <p><span class="bolder">Artifact ID:</span> {{ conflict.firstOccurance.ArtifactId }}</p>
                  </div>
                </div>
                <div class="grid-container" v-for="(obj, secondindex) in conflict.conflicts" :key="secondindex"
                     style="margin: 0; overflow: auto">
                  <div class="alert alert-light rrc"
                       style="border: black solid 1px;color: black;">
                    <p class="bolder">Version: <br><span
                        style="font-weight: normal">{{ conflict.firstOccurance.Version }}</span>
                    </p>

                    <button class="btn btn-outline-dark rrc" style="width: 100%; padding: 10px; margin: 0"
                            @click="conflictTreeView(conflictObj[firstindex].firstOccuranceJsonMap)">
                      See the project structure containing this dependency
                    </button>
                  </div>
                  <div class="alert alert-light rrc"
                       style="border: black solid 1px;color: black;">
                    <p class="bolder">Version: <br> <span
                        style="font-weight: normal">{{ obj.Version }}</span></p>
                    <button class="btn btn-outline-dark rrc" style="width: 100%; padding: 10px; margin: 0"
                            @click="conflictTreeView(conflict.jsonMap)">
                      See the project structure containing this dependency
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm col-md">
        <JsonTree class="json-tree-root json-tree-value rrc" :data="dataObj"></JsonTree>
        <button class="btn btn-secondary rrc" style="width: 100%; margin-top: 15px"
                @click="fullTreeView" v-if="treeview">
          Show the full tree instead
        </button>
      </div>
    </div>
    <div class="footer pt-5 pb-4" style="text-align: center">
      Developed by Kenneth Lindalen <br>
      <a href="https://www.linkedin.com/in/kenneth-lindalen-1ba35a187/"><img
          src="./assets/icons/linkedin-brands.svg" alt="" class="social-icons"></a>
      <a href="https://github.com/KennethLindalen"><img src="./assets/icons/github-brands.svg" alt=""
                                                        class="social-icons"></a>
      <a class="ml-1" href="https://www.buymeacoffee.com/kennethlindalen"><img
          src="./assets/icons/buymeacoffe.svg" alt=""></a>

    </div>
  </div>
</template>

<script>
import JsonTree from 'vue-json-tree'
import FileReader from "@/components/FileReader";
import Axios from 'axios'

export default {
  name: 'App',
  components: {
    JsonTree,
    FileReader,
  },
  data() {
    return {
      file: "",
      test: [],
      dataObj: {
        "Hello": "On this website you can upload your maven dependency tree to see whether you have conflicts in your builds.",
      },
      conflictObj: [],
      conflictCount: 0,
      errorMsg: "",
      dataObjCopy: {},
      treeview: false
    }
  },
  methods: {
    sendData: function () {
      let file_data;
      let response_tree;
      let response_conflicts;
      file_data = this.file.split("\n");
      for (let i = 0; i < file_data.length; i++) {
        file_data[i] = file_data[i].replace("\\", "\\\\")
      }
      Axios.post("https://mvnnavigatorbackend.herokuapp.com/", {
        input: file_data
      })
          .then(response => {
                response_tree = response.data.jsonTree;
                response_conflicts = response.data.conflictPOJOS;
                this.dataObj = response_tree;
                this.dataObjCopy = this.dataObj;
                this.conflictObj = response_conflicts;
                this.conflictCount = response_conflicts.length;
              }
          )
    },
    conflictTreeView: function (content) {
      this.dataObj = content;
      this.treeview = true;
    },
    fullTreeView: function () {
      this.dataObj = this.dataObjCopy;
      this.treeview = false;
    }
  },
}
</script>

<style>
body {
  background-color: lightskyblue;
}

#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
  margin-top: 60px;
  background-color: lightskyblue;
}

.json-tree-root {
  min-width: 0;
  height: 75vh;
  overflow: auto;
  margin-top: 0;
}

.json-tree-value {
  overflow: auto visible;
  white-space: inherit;
}

ul {
  list-style-type: none;
}

.bolder {
  font-weight: bold;
}

.social-icons {
  width: 20px;
}

.grid-container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-gap: 10px;
}

.rrc {
  border-radius: 0;
}

</style>
